### ISSUE TITLE
Release of Version 5.9 for linux-64

### ISSUE THREAD

**Issue by chrros95** [conda-forge/zsh-feedstock#12]
### Comment:

Hi,

thank you for maintaining this package.
The release of 5.9 was quite a while ago, and the packages for ppc64le and arch64 have been published.

So i wondered if it's possible to release it for x86_64 as well?
I'm asking because it stuck at 5.8 and I'm running in a Bug that is solved with 5.9.

Regards

Christian

**Comment by matthiasdiener** [comment]
Thanks for pointing out the issue! It should be fixed now.
